# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: hlf-cc-dev

release:
  name_template: "Version {{.Version}}"
  github:
    owner: kfsoftware
    name: hlf-cc-dev
  extra_files:
    - glob: "*.minisig"
    - glob: "*.zip"

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  -
    id: hlf-cc-dev
    dir: hlf-cc-dev
    binary: hlf-cc-dev
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Tag}}
    flags:
      - -trimpath

dockers:
  -
    # GOOS of the built binary that should be used.
    goos: linux
    # GOARCH of the built binary that should be used.
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "quay.io/kfsoftware/hlf-cc-dev:{{ .Tag }}"
      - "quay.io/kfsoftware/hlf-cc-dev:latest"
    extra_files:
      - LICENSE
      - README.md
      - CREDITS
