// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kfsoftware/hlf-cc-dev/ent/chaincode"
	"github.com/kfsoftware/hlf-cc-dev/ent/tenant"
)

// ChaincodeCreate is the builder for creating a Chaincode entity.
type ChaincodeCreate struct {
	config
	mutation *ChaincodeMutation
	hooks    []Hook
}

// SetPackageId sets the "packageId" field.
func (cc *ChaincodeCreate) SetPackageId(s string) *ChaincodeCreate {
	cc.mutation.SetPackageId(s)
	return cc
}

// SetChannelId sets the "channelId" field.
func (cc *ChaincodeCreate) SetChannelId(s string) *ChaincodeCreate {
	cc.mutation.SetChannelId(s)
	return cc
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (cc *ChaincodeCreate) SetTenantID(id int) *ChaincodeCreate {
	cc.mutation.SetTenantID(id)
	return cc
}

// SetNillableTenantID sets the "tenant" edge to the Tenant entity by ID if the given value is not nil.
func (cc *ChaincodeCreate) SetNillableTenantID(id *int) *ChaincodeCreate {
	if id != nil {
		cc = cc.SetTenantID(*id)
	}
	return cc
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (cc *ChaincodeCreate) SetTenant(t *Tenant) *ChaincodeCreate {
	return cc.SetTenantID(t.ID)
}

// Mutation returns the ChaincodeMutation object of the builder.
func (cc *ChaincodeCreate) Mutation() *ChaincodeMutation {
	return cc.mutation
}

// Save creates the Chaincode in the database.
func (cc *ChaincodeCreate) Save(ctx context.Context) (*Chaincode, error) {
	var (
		err  error
		node *Chaincode
	)
	if len(cc.hooks) == 0 {
		if err = cc.check(); err != nil {
			return nil, err
		}
		node, err = cc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ChaincodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cc.check(); err != nil {
				return nil, err
			}
			cc.mutation = mutation
			if node, err = cc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(cc.hooks) - 1; i >= 0; i-- {
			if cc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ChaincodeCreate) SaveX(ctx context.Context) *Chaincode {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ChaincodeCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ChaincodeCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ChaincodeCreate) check() error {
	if _, ok := cc.mutation.PackageId(); !ok {
		return &ValidationError{Name: "packageId", err: errors.New(`ent: missing required field "packageId"`)}
	}
	if v, ok := cc.mutation.PackageId(); ok {
		if err := chaincode.PackageIdValidator(v); err != nil {
			return &ValidationError{Name: "packageId", err: fmt.Errorf(`ent: validator failed for field "packageId": %w`, err)}
		}
	}
	if _, ok := cc.mutation.ChannelId(); !ok {
		return &ValidationError{Name: "channelId", err: errors.New(`ent: missing required field "channelId"`)}
	}
	return nil
}

func (cc *ChaincodeCreate) sqlSave(ctx context.Context) (*Chaincode, error) {
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (cc *ChaincodeCreate) createSpec() (*Chaincode, *sqlgraph.CreateSpec) {
	var (
		_node = &Chaincode{config: cc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: chaincode.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: chaincode.FieldID,
			},
		}
	)
	if value, ok := cc.mutation.PackageId(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: chaincode.FieldPackageId,
		})
		_node.PackageId = value
	}
	if value, ok := cc.mutation.ChannelId(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: chaincode.FieldChannelId,
		})
		_node.ChannelId = value
	}
	if nodes := cc.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chaincode.TenantTable,
			Columns: []string{chaincode.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: tenant.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tenant_chaincodes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChaincodeCreateBulk is the builder for creating many Chaincode entities in bulk.
type ChaincodeCreateBulk struct {
	config
	builders []*ChaincodeCreate
}

// Save creates the Chaincode entities in the database.
func (ccb *ChaincodeCreateBulk) Save(ctx context.Context) ([]*Chaincode, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Chaincode, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChaincodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ChaincodeCreateBulk) SaveX(ctx context.Context) []*Chaincode {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ChaincodeCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ChaincodeCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
