// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kfsoftware/hlf-cc-dev/ent/chaincode"
	"github.com/kfsoftware/hlf-cc-dev/ent/predicate"
	"github.com/kfsoftware/hlf-cc-dev/ent/tenant"
)

// ChaincodeUpdate is the builder for updating Chaincode entities.
type ChaincodeUpdate struct {
	config
	hooks    []Hook
	mutation *ChaincodeMutation
}

// Where appends a list predicates to the ChaincodeUpdate builder.
func (cu *ChaincodeUpdate) Where(ps ...predicate.Chaincode) *ChaincodeUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetPackageId sets the "packageId" field.
func (cu *ChaincodeUpdate) SetPackageId(s string) *ChaincodeUpdate {
	cu.mutation.SetPackageId(s)
	return cu
}

// SetChannelId sets the "channelId" field.
func (cu *ChaincodeUpdate) SetChannelId(s string) *ChaincodeUpdate {
	cu.mutation.SetChannelId(s)
	return cu
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (cu *ChaincodeUpdate) SetTenantID(id int) *ChaincodeUpdate {
	cu.mutation.SetTenantID(id)
	return cu
}

// SetNillableTenantID sets the "tenant" edge to the Tenant entity by ID if the given value is not nil.
func (cu *ChaincodeUpdate) SetNillableTenantID(id *int) *ChaincodeUpdate {
	if id != nil {
		cu = cu.SetTenantID(*id)
	}
	return cu
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (cu *ChaincodeUpdate) SetTenant(t *Tenant) *ChaincodeUpdate {
	return cu.SetTenantID(t.ID)
}

// Mutation returns the ChaincodeMutation object of the builder.
func (cu *ChaincodeUpdate) Mutation() *ChaincodeMutation {
	return cu.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (cu *ChaincodeUpdate) ClearTenant() *ChaincodeUpdate {
	cu.mutation.ClearTenant()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChaincodeUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		if err = cu.check(); err != nil {
			return 0, err
		}
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ChaincodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cu.check(); err != nil {
				return 0, err
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChaincodeUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChaincodeUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChaincodeUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ChaincodeUpdate) check() error {
	if v, ok := cu.mutation.PackageId(); ok {
		if err := chaincode.PackageIdValidator(v); err != nil {
			return &ValidationError{Name: "packageId", err: fmt.Errorf("ent: validator failed for field \"packageId\": %w", err)}
		}
	}
	return nil
}

func (cu *ChaincodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   chaincode.Table,
			Columns: chaincode.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: chaincode.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.PackageId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: chaincode.FieldPackageId,
		})
	}
	if value, ok := cu.mutation.ChannelId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: chaincode.FieldChannelId,
		})
	}
	if cu.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chaincode.TenantTable,
			Columns: []string{chaincode.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: tenant.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chaincode.TenantTable,
			Columns: []string{chaincode.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: tenant.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chaincode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// ChaincodeUpdateOne is the builder for updating a single Chaincode entity.
type ChaincodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChaincodeMutation
}

// SetPackageId sets the "packageId" field.
func (cuo *ChaincodeUpdateOne) SetPackageId(s string) *ChaincodeUpdateOne {
	cuo.mutation.SetPackageId(s)
	return cuo
}

// SetChannelId sets the "channelId" field.
func (cuo *ChaincodeUpdateOne) SetChannelId(s string) *ChaincodeUpdateOne {
	cuo.mutation.SetChannelId(s)
	return cuo
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (cuo *ChaincodeUpdateOne) SetTenantID(id int) *ChaincodeUpdateOne {
	cuo.mutation.SetTenantID(id)
	return cuo
}

// SetNillableTenantID sets the "tenant" edge to the Tenant entity by ID if the given value is not nil.
func (cuo *ChaincodeUpdateOne) SetNillableTenantID(id *int) *ChaincodeUpdateOne {
	if id != nil {
		cuo = cuo.SetTenantID(*id)
	}
	return cuo
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (cuo *ChaincodeUpdateOne) SetTenant(t *Tenant) *ChaincodeUpdateOne {
	return cuo.SetTenantID(t.ID)
}

// Mutation returns the ChaincodeMutation object of the builder.
func (cuo *ChaincodeUpdateOne) Mutation() *ChaincodeMutation {
	return cuo.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (cuo *ChaincodeUpdateOne) ClearTenant() *ChaincodeUpdateOne {
	cuo.mutation.ClearTenant()
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChaincodeUpdateOne) Select(field string, fields ...string) *ChaincodeUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Chaincode entity.
func (cuo *ChaincodeUpdateOne) Save(ctx context.Context) (*Chaincode, error) {
	var (
		err  error
		node *Chaincode
	)
	if len(cuo.hooks) == 0 {
		if err = cuo.check(); err != nil {
			return nil, err
		}
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ChaincodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cuo.check(); err != nil {
				return nil, err
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChaincodeUpdateOne) SaveX(ctx context.Context) *Chaincode {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChaincodeUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChaincodeUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ChaincodeUpdateOne) check() error {
	if v, ok := cuo.mutation.PackageId(); ok {
		if err := chaincode.PackageIdValidator(v); err != nil {
			return &ValidationError{Name: "packageId", err: fmt.Errorf("ent: validator failed for field \"packageId\": %w", err)}
		}
	}
	return nil
}

func (cuo *ChaincodeUpdateOne) sqlSave(ctx context.Context) (_node *Chaincode, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   chaincode.Table,
			Columns: chaincode.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: chaincode.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Chaincode.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chaincode.FieldID)
		for _, f := range fields {
			if !chaincode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chaincode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.PackageId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: chaincode.FieldPackageId,
		})
	}
	if value, ok := cuo.mutation.ChannelId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: chaincode.FieldChannelId,
		})
	}
	if cuo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chaincode.TenantTable,
			Columns: []string{chaincode.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: tenant.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chaincode.TenantTable,
			Columns: []string{chaincode.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: tenant.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Chaincode{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chaincode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
