// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/kfsoftware/hlf-cc-dev/ent/chaincode"
	"github.com/kfsoftware/hlf-cc-dev/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chaincodeFields := schema.Chaincode{}.Fields()
	_ = chaincodeFields
	// chaincodeDescPackageId is the schema descriptor for packageId field.
	chaincodeDescPackageId := chaincodeFields[0].Descriptor()
	// chaincode.PackageIdValidator is a validator for the "packageId" field. It is called by the builders before save.
	chaincode.PackageIdValidator = chaincodeDescPackageId.Validators[0].(func(string) error)
}
